### ISSUE TITLE
Loonatics 3000 addon

### ISSUE THREAD

**Issue by Dionisis1976** [techecoyote/LooNaticsAsylum#1]
Great addon, but addon will not play any magnet links for TV or Movies, comes up with error inline 7831.

Hope you can help 😊

**Comment by techecoyote** [comment]
I may decide to update Loonatics3000 for 18/19
Not in a rush for Matrix at this point. Matrix has too many bugs. Try Lu - Loonatics Unleashed for 18-Leia. Loonatics Empire 18-Leia/19-Matrix, working on as we speak. All the other additional addons I will be working on & creating a new Matrix Repo... Thank you for your comments...
