### ISSUE TITLE
Lonatics 3000 and ACME Issue Kodi 19

### ISSUE THREAD

**Issue by rehannali** [techecoyote/LooNaticsAsylum#2]
Hi, Lonatics 3000 and ACME Player and info not working on kodi 19. Kindly add support to it.

**Comment by techecoyote** [comment]
Not in a rush for Matrix at this point. Matrix has too many bugs. Try Lu - Loonatics Unleashed for 18-Leia. Loonatics Empire 18-Leia/19-Matrix, working on as we speak. All the other additional addons I will be working on & creating a new Matrix Repo... Thank you for your comments...
