### ISSUE TITLE
Can you update Elemetum addon to 0.1.86 version ? please...

### ISSUE THREAD

**Issue by Kpoodle** [techecoyote/LooNaticsAsylum#9]
in LooNatics Asylum Repository. 
Can you please update Elementum addon to 0.1.86 version? 

Thank you in advance.

**Comment by techecoyote** [comment]
Don't read me Email often. Sorry.

Here is a link to my TG grp.

https://t.me/+BKQ7ntWeJoFjMjVh
[https://cdn1.telegram-cdn.org/file/PJRlh4jXHpNwNGXGue9OfGXgJL3CoQHFXhRn2qjc1h1N1JnQujeB2ru2lS-2hqHascyPJV_Eeas3JvWkC3tyzbzJQIDdwzWCX700GzQiILqpbg9AH1WKP4ZWkopwgHRUr2gWP3i22sjyFQl4v-rO5WMQrVkBE4v5IchHTgJvsaO4b6of_MiTXTFNCmZQu_mISUv0VsmtBM7bDy28lkVnXy6QdVU2UcgeSTkGp-jaDjx50aYDJuomxO_OPvZImgPQisbafWh5bAe1_oobSuy0fX0ApAcfpffXj5UyYTAFFER87t25Bs8WnoOCgmrqPJBtWDsfynCyzl2oulP6giejdg.jpg]<https://t.me/+BKQ7ntWeJoFjMjVh>
The WareHouse<https://t.me/+BKQ7ntWeJoFjMjVh>
t.me

________________________________
From: Kpoodle ***@***.***>
Sent: Thursday, March 31, 2022 6:23 AM
To: techecoyote/LooNaticsAsylum ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [techecoyote/LooNaticsAsylum] Can you appdate Elemetum addon to v0.1.86 ? please... (Issue #9)


Elementum addon is in 0.1.58 version in LooNatics Asylum Repository.
Can you please update Elementum addon to 0.1.86 version?
Thank you in advance.

**Comment by Arthur1967** [comment]
OK I will update thank you for replying have a good night
